### ISSUE TITLE
Can click handling similar to React's go in here? 

### ISSUE THREAD

**Issue by theneva** [TheKnarf/isomorphic-jsx#10]
One thing I found confusing was that the library accepts props like onClick, onBlur, and so on, but effectively throw them away.

Could the library yell at you for sending camelCased listener props, or maybe simply take the body of onClick and wrap it in a function, then change the onClick prop to a regular onclick and call that function?

**Comment by TheKnarf** [comment]
The library as it stands now got a few different use cases:

1. Generate HTML from an express server.

2. Generate HTML as a part of a static site generator.

3. Generate XML.

Creating a eslint-plugin that could complain about camelCased props is entirely possible, but for now I don't think theres any real use for it. The library isn't throwing them away, they are simply not valid html and is ignored by the browser.

One solution I was thinking about was to add a config option where you could write a callback function that could do anything it wanted when it matched with a given attribute. This could have been used both to add a rewrite capability or a simple lint / throw error. But for now I don't think this is really needed. It unnecessarily complicate what is supposed to be a simple and easy to understand library. Other libraries like Preact, GatsbyJS and Next.js offer more feature complete solutions for building application that need both Server side rendering and client side dom-diffing capabilities.

I might reverse this decision in the future, if we have a compelling use-case, but even then I'd still like to keep the library as simple as possible.
