### ISSUE TITLE
Support components rendering arrays

### ISSUE THREAD

**Issue by theneva** [TheKnarf/isomorphic-jsx#3]
```
const Hi = () => [
	<div/>,
  	<p/>
]

const lol = <Hi />
```

`lol` should now contain the string `"<div/><p/>"`, but instead contains an array.

**Comment by TheKnarf** [comment]
Will fix, todo:

- [ ] Write a test case for it
- [ ] Fix the bug
- [ ] Make a new minor release

**Comment by TheKnarf** [comment]
Fixed in c1b77649b26f5122bf411e6de146f8137ac19b94
