### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by TheKnarf** [TheKnarf/isomorphic-jsx#9]
I would like for this project to have a nice & clean logo.

**Comment by aidenfrost5** [comment]
what kind of a logo are you looking for 
i am a graphics designer i can help you with that for free

**Comment by TheKnarf** [comment]
The two projects that is most similar to this one is [React](https://reactjs.org/) and [Preact](https://github.com/developit/preact). Their logo's is kinda similare:

![react](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1024px-React-icon.svg.png)
![preact](https://camo.githubusercontent.com/31415a8c001234dbf4875c2c5a44b646fb9338b4/68747470733a2f2f63646e2e7261776769742e636f6d2f646576656c6f7069742f62343431366435633932623734336462616563316536386263346332376364612f7261772f333233356463353038663765623833346562663438343138616561323132613035646631336462312f7072656163742d6c6f676f2d7472616e732e737667)

`isomorphic jsx` on the other hand is a much simpler project, and much more static than react and preact. I'd like for something fairly simple and clean that feature the name of the project. In my mind I was picturing something derived from the js logo:

![js](https://cdn.worldvectorlogo.com/logos/javascript.svg)

Maybe using two rectangles instead of one, the first for isomorphic and the second for jsx. Put I'm happy with any suggestions.

**Comment by TheKnarf** [comment]
@aidenfrost5 I created a [Gitter chat room](https://gitter.im/isomorphic-jsx/Lobby), if you have any time I'd love to chat some about what we can do about a logo. I've also been trying out a few ideas by myself, but none that I'm to happy with.
